(()=>{'use strict';
const root=document.documentElement;
const style=document.createElement('link');style.rel='stylesheet';style.href='/css/experience.css?v=20261010k';document.head.append(style);
const controls=document.createElement('div');controls.className='experience-controls';controls.innerHTML='<button type="button" class="sound-toggle" aria-pressed="false">Sound off <span aria-hidden="true">◌</span></button><label class="sound-volume">Volume <input type="range" min="0" max="100" value="25" aria-label="Sound volume"></label>';document.body.append(controls);
const button=controls.querySelector('button'),volume=controls.querySelector('input');
let ctx,master,enabled=false,lastTone=0;
function build(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('Audio unavailable');ctx=new AC();master=ctx.createGain();master.gain.value=0;master.connect(ctx.destination);
[110,164.81,220,261.63].forEach((frequency,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain(),lfo=ctx.createOscillator(),depth=ctx.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.value=.025;lfo.frequency.value=.055+i*.018;depth.gain.value=.009;lfo.connect(depth);depth.connect(gain.gain);osc.connect(gain);gain.connect(master);osc.start();lfo.start();});}
function level(){if(master)master.gain.setTargetAtTime(enabled&&!document.hidden?Number(volume.value)/100:0,ctx.currentTime,.18);}
function tone(click=false){if(!enabled||!ctx||document.hidden)return;const now=ctx.currentTime;if(now-lastTone<.09)return;lastTone=now;const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(click?440:660,now);o.frequency.exponentialRampToValueAtTime(click?880:440,now+.12);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.045,now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+.16);o.connect(g);g.connect(master);o.start(now);o.stop(now+.18);o.onended=()=>{o.disconnect();g.disconnect();};}
button.addEventListener('click',async()=>{try{if(!ctx)build();if(ctx.state==='suspended')await ctx.resume();enabled=!enabled;button.setAttribute('aria-pressed',String(enabled));button.innerHTML=enabled?'Sound on <span aria-hidden="true">≋</span>':'Sound off <span aria-hidden="true">◌</span>';controls.classList.toggle('enabled',enabled);level();if(enabled)tone(true);}catch{button.textContent='Sound unavailable';button.disabled=true;}});
volume.addEventListener('input',level);document.addEventListener('visibilitychange',level);window.addEventListener('pagehide',()=>{enabled=false;level();});window.addEventListener('pageshow',()=>{if(!enabled){button.setAttribute('aria-pressed','false');button.innerHTML='Sound off <span aria-hidden="true">◌</span>';controls.classList.remove('enabled');}});
document.addEventListener('pointerover',e=>{const target=e.target.closest('a,button');if(target&&!target.contains(e.relatedTarget)&&!controls.contains(target))tone();});document.addEventListener('focusin',e=>{if(e.target.closest('a,button')&&!controls.contains(e.target))tone();});document.addEventListener('click',e=>{if(e.target.closest('a')&&!controls.contains(e.target))tone(true);});
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
if(!reduced.matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.section-head,.episode,.clip,.split,.income-card,.project-panel h2').forEach(el=>{el.classList.add('reveal');observer.observe(el);});}
const hero=document.querySelector('.hero');if(hero){const visual=document.createElement('div');visual.className='orbital-scene';visual.setAttribute('aria-hidden','true');visual.innerHTML='<div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="orbit orbit-c"></div><div class="orb-core"></div>';hero.prepend(visual);const eyebrow=hero.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent='Every round has a turning point.';const hint=document.createElement('a');hint.className='scene-cue';hint.href='#clips';hint.textContent='Find your next moment ↓';hero.append(hint);}
})();
